### ISSUE TITLE
Can't compile for varnish 4.1 on OSX Yosemite

### ISSUE THREAD

**Issue by quintonparker** [varnish/libvmod-vsthrottle#10]
Getting this error message. Please help

~/Downloads/libvmod-vsthrottle-4.1 quinton.parker@q

> make
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
> Making all in src
> /bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/local/Cellar/varnish/4.1.0/include/varnish -Wall -Werror   -g -O2 -MT vmod_vsthrottle.lo -MD -MP -MF .deps/vmod_vsthrottle.Tpo -c -o vmod_vsthrottle.lo vmod_vsthrottle.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/varnish/4.1.0/include/varnish -Wall -Werror -g -O2 -MT vmod_vsthrottle.lo -MD -MP -MF .deps/vmod_vsthrottle.Tpo -c vmod_vsthrottle.c  -fno-common -DPIC -o .libs/vmod_vsthrottle.o
> vmod_vsthrottle.c:136:5: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>         AZ(clock_gettime(CLOCK_MONOTONIC, &ts));
>            ^
> /usr/local/Cellar/varnish/4.1.0/include/varnish/vas.h:74:31: note: expanded from macro 'AZ'
> # define AZ(foo)         do { assert((foo) == 0); } while (0)
> 
> ```
>                                  ^
> ```
> 
> /usr/local/Cellar/varnish/4.1.0/include/varnish/vas.h:58:8: note: expanded from macro 'assert'
>         if (!(e)) {                                                     \
>               ^
> vmod_vsthrottle.c:136:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
>         AZ(clock_gettime(CLOCK_MONOTONIC, &ts));
>                          ^
> /usr/local/Cellar/varnish/4.1.0/include/varnish/vas.h:74:31: note: expanded from macro 'AZ'
> # define AZ(foo)         do { assert((foo) == 0); } while (0)
> 
> ```
>                                  ^
> ```
> 
> /usr/local/Cellar/varnish/4.1.0/include/varnish/vas.h:58:8: note: expanded from macro 'assert'
>         if (!(e)) {                                                     \
>               ^
> 2 errors generated.
> make[2]: **\* [vmod_vsthrottle.lo] Error 1
> make[1]: **\* [all-recursive] Error 1
> make: **\* [all] Error 2

**Comment by fgsch** [comment]
Fixed via https://github.com/varnish/libvmod-vsthrottle/pull/11.
