### ISSUE TITLE
Allow to disable rst2man

### ISSUE THREAD

**Issue by george-angel** [varnish/libvmod-vsthrottle#12]
Trying to build this plugin in docker with alpine linux as base image.

I'm currently stuck at the `make` step. With error stating I am missing rst2man. I happened upon this issue: https://github.com/varnish/hitch/issues/47

Could something similar be applied to vsthrottle or does it exist and I cannot find that flag?

Thank you

**Comment by dridi** [comment]
Hi @Zapadlo,

Do you want to try and fix it? I'd review your pull request.

Cheers

**Comment by lkarsten** [comment]
Hi. 

vmod-vsthrottle source has been merged into https://github.com/varnish/varnish-modules .

If you choose to follow up on this, please file the pull request there instead.
