### ISSUE TITLE
Success w/ a caveat

### ISSUE THREAD

**Issue by allklier** [varnish/libvmod-vsthrottle#8]
I successfully added vsthrottle to our Varnish 4 install. Very happy to have found it and to get it working.

The caveat is that it doesn't completely fix the use case. Our other server is locked down with Apache mod_qos to protect it against the relentless bots trying to guess Wordpress passwords (don't get me started, it's a reality I have to live with). To protect Apache we use a rule that limits all incoming traffic to a max of 35 concurrent (!) connections per IP.

With Varnish in front on our second server that rule had to be disabled because Varnish keeps many connections open to the backend, which is a good thing.

So I'm trying to migrate the max concurrent IP functionality into Varnish, which is where this vmod comes in. But it doesn't measure concurrent connections per IP, but total connections over a period of time. Since our site has many static requests for images, css, js, which are really harmless compared to the resource hungry php core page requests, I have to use a high limit for vsthrottle (right now set at 100 over 2s), otherwise I'm missing images on the page. But that's a high limit for concurrent connections.

Would there be an easy way to adapt vsthrottle into a mode where a token is credited back to the bucket upon vcl_deliver or appropriate event. That way the hash would reflect concurrent count and could enforce not only timebound connection limits but concurrent connection limits?

Looking at the code a variation of is_denied that doesn't use a limit and sets up a bucket that doesn't use time as a hash component, just key parameter. Then set up a sister function called from VCL upon backend_response that operates the reverse. Should be straight forward. Might take a stab at it if I can get a break between tasks.

**Comment by perbu** [comment]
Hi.
I think you might be overcomplicating this. What you want to do is to only throttle POST requests per IP address. So something like:

> sub vcl_recv {
>        if (req.method == "POST") {
>           if (vsthrottle.is_denied(client.ip, 5, 20s)) {
> ..

This would limit each unique IP to max 5 POSTs per 20 seconds. Would this solve your problem?

**Comment by allklier** [comment]
Good point. That would solve have the problem, where they're guessing passwords. They also run bots that look for specific vulnerabilities with random URLs. Those are GET requests. But since the pages don't exist they punch through to Apache, which has to spin up a PHP child look in the database only to determine that it was fake. It's the PHP children in rapid fire that cause the problems when the server runs out of resources. We can sometimes get upwards of thousands of requests in an hour looking for a needle in a haystack.

But a variation that might work, similar to our mod_qos rules is to limit the number of non-static requests regardless of GET/POST method to a smaller number. I'll have a look if that might work in VCL as well.

**Comment by danielbeardsley** [comment]
Sounds like a great feature that I'd love to see as well. It'd be helpful if this was closed with a reason: i.e. won't-fix, maybe-someday, version-x

**Comment by gquintard** [comment]
@danielbeardsley : looks like a wontfix, as the goal is achievable via vcl without jumping through hoops.

**Comment by allklier** [comment]
@gquintard @danielbeardsley That depends on what the goal is. You can get close, but it is still a cruder / less elegant solution and requires more margin of error. There is a difference between limiting concurrent connections vs. total connections over a specified time limit. We end up under-utilizing the host because resources are tied to concurrent usage.

**Comment by danielbeardsley** [comment]
Exactly. This only limits the count of new connections, regardless of how long they last and puts no limit on the number of concurrent connections.That would be pretty useful.

**Comment by dridi** [comment]
I tend to agree with both @allklier @perbu @danielbeardsley and @gquintard here.

With the current model we have something somewhat limited that can do a lot thanks to the flexibility of VCL.

Being able to count down in certain situations would also help but at the same time we have moving counters that eventually time out. We don't want the count down to become a complexity hog. Also, how can we count client connections since VCL works on a per-request basis?

If someone comes up with a simple solution, I'll spend time on the review. In this case please open a pull request on https://github.com/varnish/varnish-modules where the module lives from now on.

**Comment by allklier** [comment]
There is conceptually an ultra simple solution. Since vsthrottle uses the token bucket algorithm, dealing with concurrent vs. basic connections could be simply a matter of crediting the token back.

If is_denied removes a token from the keyed bucket, there could be a sister function, let's say is_complete that has to be called with the identical key from vcl_resp which would credit the token back to the same bucket.

Given that this would require explicit calling of the credit, there is no complexity or burden unless concurrent connections are monitored. With vcl_resp replenishing tokens the limit can be set tighter to reflect resource capacity rather than padding as is needed right now.

Unfortunately I'm in the middle of other projects and can't code that right now. If someone has time, that would be great, otherwise I might get back to it later. In theory it should be all but a few lines.

**Comment by gquintard** [comment]
You'll still have to remember all the the "is_denied" calls though.
