### ISSUE TITLE
Symbol not found: 'req.request' (expected type BOOL):

### ISSUE THREAD

**Issue by blindpet** [varnish/libvmod-vsthrottle#9]
Having trouble with a rule that worked in varnish 3 with throttle

```
Prevent users from making excessive POST requests that aren't for admin-ajax
if(((vsthrottle.is_denied(req.http.X-Actual-IP, 15, 10s) && (!req.url ~ "admin-ajax.php") &&     (req.request == "POST")) {
       return (synth(429, "Too Many Requests"));
       # Use shield vmod to reset connection
       shield.conn_reset();
}
```

**Comment by aondio** [comment]
Hi,
req.request has become req.method in varnish 4.

**Comment by Francois-v3** [comment]
Hi,

req.request becames req.method in varnish 4.

François Veux.

Le 28/10/2015 21:05, blindpet a écrit :

> Having trouble with a rule that worked in varnish 3 with throttle
> 
> |Prevent users from making excessive POST requests that aren't for 
> admin-ajax if(((vsthrottle.is_denied(req.http.X-Actual-IP, 15, 10s) && 
> (!req.url ~ "admin-ajax.php") && (req.request == "POST")) { return 
> (synth(429, "Too Many Requests")); # Use shield vmod to reset 
> connection shield.conn_reset(); } |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/varnish/libvmod-vsthrottle/issues/9.

## 

François Veux - +33633267508

**Comment by blindpet** [comment]
Thank you very much for the support.

Made good use of this for protecting Wordpress, feel free to link to the [walkthrough](http://www.htpcguides.com/wordpress-ddos-attack-protection-varnish-4-firewall/) in Wiki. I will continue to tweak as necessary but this seems good for now.
